// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQY1hw7Wy2lHhYgsxnNt7KQYvIljglwDE',
    appId: '1:872559821258:web:1e8983fd48d38962570f33',
    messagingSenderId: '872559821258',
    projectId: 'ucity-garden',
    authDomain: 'ucity-garden.firebaseapp.com',
    storageBucket: 'ucity-garden.firebasestorage.app',
    measurementId: 'G-2RLX7L1VX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZEEqku7EuyHe9qoXiz_tMvNz3vNMKcWI',
    appId: '1:872559821258:android:08b9f84034dcb894570f33',
    messagingSenderId: '872559821258',
    projectId: 'ucity-garden',
    storageBucket: 'ucity-garden.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5TPhmA4bPPFmaCuNrKk9ewrowibSUEm8',
    appId: '1:872559821258:ios:c6666454d38a63ac570f33',
    messagingSenderId: '872559821258',
    projectId: 'ucity-garden',
    storageBucket: 'ucity-garden.firebasestorage.app',
    iosBundleId: 'com.example.ucityapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5TPhmA4bPPFmaCuNrKk9ewrowibSUEm8',
    appId: '1:872559821258:ios:c6666454d38a63ac570f33',
    messagingSenderId: '872559821258',
    projectId: 'ucity-garden',
    storageBucket: 'ucity-garden.firebasestorage.app',
    iosBundleId: 'com.example.ucityapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFuOOwHkKuwPk_udI65r7CfSh4odUoO7o',
    appId: '1:872559821258:web:9fd60b7ec74b6907570f33',
    messagingSenderId: '872559821258',
    projectId: 'ucity-garden',
    authDomain: 'ucity-garden.firebaseapp.com',
    storageBucket: 'ucity-garden.firebasestorage.app',
    measurementId: 'G-B4MNB8NMPS',
  );
}
